### ISSUE TITLE
Investigate failed publish of precog/precog

### ISSUE THREAD

**Issue by rintcius** [precog/sbt-precog#130]
```
[error] /tmp/sbt-precog16684092595427387162/version.sbt:1: warning: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
[error] version in ThisBuild := "1.1.6"
[error]         ^
[info] [info] loading settings for project root from build.sbt,version.sbt ...
[info] [info] resolving key references (12618 settings) ...
[info] [info] looking for workflow definition in /tmp/sbt-precog16684092595427387162/.github/workflows
[info] [info] set current project to root (in build file:/tmp/sbt-precog16684092595427387162/)
[info] [info] Fetched metadata repository. master is now at 9a6cfaf4855e16f52fb2a9bb5901821c3812b098
[info] [error] sjsonnew.shaded.org.typelevel.jawn.IncompleteParseException: exhausted input
[info] [error] 	at sjsonnew.shaded.org.typelevel.jawn.Parser.parse(Parser.scala:366)
[info] [error] 	at sjsonnew.shaded.org.typelevel.jawn.SyncParser.parse(SyncParser.scala:23)
[info] [error] 	at sjsonnew.shaded.org.typelevel.jawn.SupportParser.$anonfun$parseFromFile$1(SupportParser.scala:24)
[info] [error] 	at scala.util.Try$.apply(Try.scala:213)
[info] [error] 	at sjsonnew.shaded.org.typelevel.jawn.SupportParser.parseFromFile(SupportParser.scala:24)
[info] [error] 	at sjsonnew.shaded.org.typelevel.jawn.SupportParser.parseFromFile$(SupportParser.scala:23)
[info] [error] 	at sjsonnew.support.scalajson.unsafe.Parser$.parseFromFile(Parser.scala:8)
[info] [error] 	at sbt.util.FileInput.read(Input.scala:53)
[info] [error] 	at sbt.util.FileBasedStore.read(CacheStore.scala:86)
[info] [error] 	at precog.ManagedVersions.safeRead(ManagedVersions.scala:88)
[info] [error] 	at precog.ManagedVersions.get(ManagedVersions.scala:43)
[info] [error] 	at precog.SbtPrecogBase.$anonfun$updateDependencies$2(SbtPrecogBase.scala:501)
[info] [error] 	at precog.SbtPrecogBase.$anonfun$updateDependencies$2$adapted(SbtPrecogBase.scala:499)
[info] [error] 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:141)
[info] [error] 	at precog.SbtPrecogBase.updateDependencies(SbtPrecogBase.scala:499)
[info] [error] 	at precog.SbtPrecogBase.$anonfun$projectSettings$8(SbtPrecogBase.scala:433)
[info] [error] 	at precog.SbtPrecogBase.$anonfun$projectSettings$8$adapted(SbtPrecogBase.scala:432)
[info] [error] 	at scala.Option.map(Option.scala:230)
[info] [error] 	at precog.SbtPrecogBase.$anonfun$projectSettings$7(SbtPrecogBase.scala:432)
[info] [error] 	at precog.SbtPrecogBase.$anonfun$projectSettings$7$adapted(SbtPrecogBase.scala:428)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[info] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[info] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[info] [error] 	at sbt.Execute.work(Execute.scala:291)
[info] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info] [error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[info] [error] (trickleUpdateDependencies) sjsonnew.shaded.org.typelevel.jawn.IncompleteParseException: exhausted input
[info] [error] Total time: 1 s, completed Sep 16, 2021, 8:45:44 AM
[info] 
[error] precog.algebras.Runner$RunnerException: sbt trickleUpdateDependencies exit code 1
[error] 	at precog.interpreters.SyncRunner.$anonfun$run$4(SyncRunner.scala:68)
[error] 	at precog.interpreters.SyncRunner.$anonfun$run$4$adapted(SyncRunner.scala:68)
[error] 	at cats.MonadError.$anonfun$ensureOr$1(MonadError.scala:20)
[error] 	at flatMap @ precog.interpreters.SyncRunner.$qmark(SyncRunner.scala:75)
[error] 	at ensureOr$extension @ precog.interpreters.SyncRunner.$anonfun$run$3(SyncRunner.scala:68)
[error] 	at map @ precog.interpreters.SyncRunner.$anonfun$run$3(SyncRunner.scala:67)
[error] 	at flatMap @ precog.interpreters.SyncRunner.$anonfun$run$2(SyncRunner.scala:66)
[error] 	at flatMap @ precog.interpreters.SyncRunner.$anonfun$run$1(SyncRunner.scala:65)
[error] 	at flatMap @ precog.interpreters.SyncRunner.run(SyncRunner.scala:64)
[error] 	at map @ precog.AutoBump.$anonfun$tryUpdateDependencies$6(AutoBump.scala:370)
[error] 	at point @ precog.AutoBump$.getSbt(AutoBump.scala:235)
[error] 	at flatMap @ precog.AutoBump.$anonfun$tryUpdateDependencies$5(AutoBump.scala:369)
[error] 	at flatMap @ precog.interpreters.SyncRunner.$qmark(SyncRunner.scala:75)
[error] 	at ensureOr$extension @ precog.interpreters.SyncRunner.$anonfun$run$3(SyncRunner.scala:68)
[error] 	at map @ precog.interpreters.SyncRunner.$anonfun$run$3(SyncRunner.scala:67)
[error] 	at flatMap @ precog.interpreters.SyncRunner.$anonfun$run$2(SyncRunner.scala:66)
[error] 	at flatMap @ precog.interpreters.SyncRunner.$anonfun$run$1(SyncRunner.scala:65)
[error] 	at flatMap @ precog.interpreters.SyncRunner.run(SyncRunner.scala:64)
[error] 	at flatMap @ precog.AutoBump.$anonfun$tryUpdateDependencies$4(AutoBump.scala:368)
[error] (trickleCreatePullRequests) precog.algebras.Runner$RunnerException: sbt trickleUpdateDependencies exit code 1
[error] Total time: 36 s, completed Sep 16, 2021, 8:45:45 AM

Error: Process completed with exit code 1.
```

**Comment by rintcius** [comment]
<0>
